### ISSUE TITLE
Issues with command line php

### ISSUE THREAD

**Issue by jhirbour** [benjaminoakes/homesick-vi-everywhere#2]
First ZOMG why am I running command line php apps... don't ask.

I recently added homesick-vi-everywhere to my shell setup. 

The line `bind "set completion-ignore-case on"` (https://github.com/benjaminoakes/homesick-vi-everywhere/blob/master/home/.editrc#L2)

Causes php to output `Unbound extended key "set completion-ignore-case on"` every time a php command line script is run. If I comment it out then php behaves as expected.

Sample php command line to test with:

```
#!/usr/bin/env php
<?php
echo "this is php\n";
?>
```
- System information:

```
 $>cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.4 (Santiago)
$>uname -a
Linux some_server_name_here 2.6.32-504.el6.x86_64 #1 SMP Tue Sep 16 01:56:35 EDT 2014 x86_64 x86_64 x86_64 GNU/Linux

$>rpm -qa | grep php
php-mysql-5.4.21-2.el6.remi.x86_64
php-5.4.21-2.el6.remi.x86_64
php-soap-5.4.21-2.el6.remi.x86_64
php-bcmath-5.4.21-2.el6.remi.x86_64
php-cli-5.4.21-2.el6.remi.x86_64
php-pdo-5.4.21-2.el6.remi.x86_64
php-mbstring-5.4.21-2.el6.remi.x86_64
php-xml-5.4.21-2.el6.remi.x86_64
newrelic-php5-4.10.1.62-1.x86_64
php-pear-Image-GraphViz-1.3.0-5.el6.remi.noarch
php-gd-5.4.21-2.el6.remi.x86_64
php-ioncube-loader-4.4.4-1.el6.remi.x86_64
php-devel-5.4.21-2.el6.remi.x86_64
php-imap-5.4.21-2.el6.remi.x86_64
php-mcrypt-5.4.21-2.el6.remi.x86_64
php-process-5.4.21-2.el6.remi.x86_64
newrelic-php5-common-4.10.1.62-1.noarch
php-pecl-memcache-3.0.8-1.el6.remi.x86_64
php-pear-1.9.4-23.el6.remi.noarch
php-common-5.4.21-2.el6.remi.x86_64

$>rpm -qa | grep readline
readline-devel-6.0-4.el6.x86_64
readline-6.0-4.el6.x86_64
```

**Comment by lourinaldi** [comment]
Necroing: 

I was having this problem with ruby (homebrew, specifically) and used option #1 on this page to fix it:

https://github.com/guard/guard/wiki/Add-Readline-support-to-Ruby-on-Mac-OS-X
